config/routes.rb
Rails.application.routes.draw do
  resources :contactbooks

end

app/models/contactbook.rb
class Contactbook < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contactbooks_controller.rb
class ContactbooksController < ApplicationController
  before_action :set_contactbook, only: [:show, :edit, :update, :destroy]

  # GET /contactbooks
  # GET /contactbooks.json
  def index
    @contactbooks = Contactbook.all
  end

  # GET /contactbooks/1
  # GET /contactbooks/1.json
  def show
  end

  # GET /contactbooks/new
  def new
    @contactbook = Contactbook.new
  end

  # GET /contactbooks/1/edit
  def edit
  end

  # POST /contactbooks
  # POST /contactbooks.json
  def create
    @contactbook = Contactbook.new(contactbook_params)

    respond_to do |format|
      if @contactbook.save
        format.html { redirect_to @contactbook, notice: 'Contactbook was successfully created.' }
        format.json { render :show, status: :created, location: @contactbook }
      else
        format.html { render :new }
        format.json { render json: @contactbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactbooks/1
  # PATCH/PUT /contactbooks/1.json
  def update
    respond_to do |format|
      if @contactbook.update(contactbook_params)
        format.html { redirect_to @contactbook, notice: 'Contactbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @contactbook }
      else
        format.html { render :edit }
        format.json { render json: @contactbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactbooks/1
  # DELETE /contactbooks/1.json
  def destroy
    @contactbook.destroy
    respond_to do |format|
      format.html { redirect_to contactbooks_url, notice: 'Contactbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contactbook
      @contactbook = Contactbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contactbook_params
      params.require(:contactbook).permit(:name, :address, :city, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactbooks_helper.rb
module ContactbooksHelper
end

app/views/contactbooks/_form.html.erb
<%= form_for(@contactbook) do |f| %>
  <% if @contactbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contactbook.errors.count, "error") %> prohibited this contactbook from being saved:</h2>

      <ul>
      <% @contactbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contactbooks/edit.html.erb
<h1>Editing Contactbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @contactbook %> |
<%= link_to 'Back', contactbooks_path %>

app/views/contactbooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contactbooks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contactbooks.each do |contactbook| %>
      <tr>
        <td><%= contactbook.name %></td>
        <td><%= contactbook.address %></td>
        <td><%= contactbook.city %></td>
        <td><%= contactbook.phone %></td>
        <td><%= contactbook.email %></td>
        <td><%= link_to 'Show', contactbook %></td>
        <td><%= link_to 'Edit', edit_contactbook_path(contactbook) %></td>
        <td><%= link_to 'Destroy', contactbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contactbook', new_contactbook_path %>

app/views/contactbooks/new.html.erb
<h1>New Contactbook</h1>

<%= render 'form' %>

<%= link_to 'Back', contactbooks_path %>

app/views/contactbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contactbook.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contactbook.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @contactbook.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contactbook.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contactbook.email %>
</p>

<%= link_to 'Edit', edit_contactbook_path(@contactbook) %> |
<%= link_to 'Back', contactbooks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contact</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>